version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: signals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/signals
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: changemeplease
      STRIPE_API_KEY: ${STRIPE_API_KEY:-}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./backend
    command: python -m app.workers.worker
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/signals
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: changemeplease
      STRIPE_API_KEY: ${STRIPE_API_KEY:-}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
